### ISSUE TITLE
[Bug]: BOR with confirmation in onco_resp.R

### ISSUE THREAD

**Issue by ccctingting** [kaigu1990/stabiot#36]
In the code below, 
```
group_by(!!sym(unique_id)) %>%
filter(
  row_number() <= min(match(TRUE, .data$flag))
)
```
keeping only the first record where the flag is 'TRUE' prevents the detection of subsequent CRs, such as in the following scenario, for new added subject 9, the BOR should be CR not PR

```
adrs <- tibble::tribble(
  ~USUBJID, ~TRTSDTC,     ~ADTC,        ~AVALC,
  "9",      "2020-01-01", "2020-01-01", "PR",
  "9",      "2020-01-01", "2020-02-01", "CR",
  "9",      "2020-01-01", "2020-02-16", "NE",
  "9",      "2020-01-01", "2020-03-01", "CR",
  "9",      "2020-01-01", "2020-04-01", "CR"
) %>%
  dplyr::mutate(
    ADT = lubridate::ymd(ADTC),
    TRTSDT = lubridate::ymd(TRTSDTC),
    PARAMCD = "OVR",
    PARAM = "Overall Response by Investigator"
  ) %>%
  dplyr::select(-TRTSDTC)

derive_bor(data = adrs, ref_start_window = 28, ref_interval = 28, confirm = TRUE,max_ne = 0)

# A tibble: 1 × 8
  USUBJID ADTC       AVALC ADT        TRTSDT     PARAMCD PARAM                            AVAL
  <chr>   <chr>      <chr> <date>     <date>     <chr>   <chr>                           <dbl>
1 9       2020-01-01 PR    2020-01-01 2020-01-01 CBOR    Confirmed Best Overall Response     2
```

**Comment by ccctingting** [comment]
Hi @kaigu1990 , my point is that the program focuses on first CR sequence,  CR-NE-CR ,  it stops searching for the second CR. For instance, a CR-CR sequence from 2020-03-01 to 2020-04-01 should also be considered a confirmed CR.

**Comment by kaigu1990** [comment]
thanks! I got it, It's an unexpected issue. I will update the program as following with adding `ADTC` as a key for `group_key`. In this case, we can detect all record CRs that fulfill our conditions, and then judge how many NE can be allowed. If more than one confirmed CR are detected, only first one will be kept.
```
group_by(!!sym(unique_id), ADTC) %>%
filter(
  row_number() <= min(match(TRUE, .data$flag))
)
```

Do you think that is a solution to our questions?
